# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e978d1c38ecea42546d5dbabd8b47073bac982c5c7a6af9e65445851c323e73601d671595428157fc0935e77bb7032d490d0308488c1aa4f7030f41ee4edc24

test:
  secret_key_base: a36dc9683fef14752d419eb0e70d8c0ce59c05defa17dbd0d97a00212db9ee1d6a50c17b2033e5d5a443ff0680f223f5bb833aa4b654c8670ef761128e26493d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
